import "dotenv/config";
import { readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";

const G = "\x1b[32m";
const Y = "\x1b[33m";
const C = "\x1b[36m";
const M = "\x1b[35m";
const D = "\x1b[2m";
const B = "\x1b[1m";
const R = "\x1b[0m";

// ============================================================
// 1. Read and merge audit reports
// ============================================================

function mergeAuditReports(): string {
  const auditDir = join(process.cwd(), "audit");
  const files = readdirSync(auditDir)
    .filter((f) => f.endsWith(".md"))
    .sort();

  if (files.length === 0) {
    throw new Error("No audit reports found in audit/ directory");
  }

  console.log(`  ${C}[Audit]${R} Found ${files.length} reports:`);
  files.forEach((f) => console.log(`    ${D}• ${f}${R}`));

  // Build Table of Contents
  const toc = [
    `# Toro Platform — System Audit Report`,
    ``,
    `**Date:** ${new Date().toISOString().split("T")[0]}`,
    `**Platform:** Toro v0.1.0`,
    `**Status:** Ready for Launch`,
    ``,
    `---`,
    ``,
    `## Table of Contents`,
    ``,
  ];

  const sections: string[] = [];

  for (let i = 0; i < files.length; i++) {
    const file = files[i]!;
    const content = readFileSync(join(auditDir, file), "utf-8");

    // Extract first heading for TOC
    const heading = content.match(/^#\s+(.+)/m)?.[1] ?? file;
    toc.push(`${i + 1}. [${heading}](#tab-${i + 1})`);

    sections.push(`\n---\n\n<a id="tab-${i + 1}"></a>\n\n${content}`);
  }

  toc.push(
    ``,
    `---`,
    ``,
    `> Generated by Toro Audit System • ${new Date().toISOString()}`
  );

  return [...toc, ...sections].join("\n");
}

// ============================================================
// 2. Create Linear issue
// ============================================================

const CREATE_ISSUE_MUTATION = `
  mutation IssueCreate($input: IssueCreateInput!) {
    issueCreate(input: $input) {
      success
      issue {
        id
        identifier
        url
      }
    }
  }
`;

const TEAMS_QUERY = `
  query {
    teams {
      nodes {
        id
        name
        key
      }
    }
  }
`;

async function linearGql<T>(query: string, variables?: Record<string, unknown>): Promise<T> {
  const apiKey = process.env.LINEAR_API_KEY;
  if (!apiKey) throw new Error("LINEAR_API_KEY not set");

  const response = await fetch("https://api.linear.app/graphql", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: apiKey,
    },
    body: JSON.stringify({ query, variables }),
  });

  if (!response.ok) throw new Error(`Linear API: ${response.status}`);

  const result = (await response.json()) as { data?: T; errors?: Array<{ message: string }> };
  if (result.errors?.length) throw new Error(result.errors.map((e) => e.message).join(", "));
  if (!result.data) throw new Error("No data from Linear");
  return result.data;
}

async function findTeamId(): Promise<string> {
  if (process.env.LINEAR_TEAM_ID) return process.env.LINEAR_TEAM_ID;

  const data = await linearGql<{ teams: { nodes: Array<{ id: string; name: string }> } }>(TEAMS_QUERY);
  const toro = data.teams.nodes.find((t) => t.name.toLowerCase().includes("toro"));
  return toro?.id ?? data.teams.nodes[0]?.id ?? "";
}

async function createAuditIssue(markdown: string): Promise<{ identifier: string; url: string }> {
  const teamId = await findTeamId();

  const data = await linearGql<{
    issueCreate: { success: boolean; issue: { id: string; identifier: string; url: string } | null };
  }>(CREATE_ISSUE_MUTATION, {
    input: {
      teamId,
      title: "SYSTEM AUDIT: Ready for Launch",
      description: markdown,
      priority: 1, // Urgent
    },
  });

  const issue = data.issueCreate.issue;
  if (!data.issueCreate.success || !issue) throw new Error("Failed to create issue");
  return { identifier: issue.identifier, url: issue.url };
}

// ============================================================
// 3. Main
// ============================================================

async function main() {
  console.log(`\n${B}${M}  ⚡ TORO AUDIT PUSH${R}`);
  console.log(`${D}  Merging reports and syncing to Linear${R}\n`);

  // Merge reports
  const markdown = mergeAuditReports();
  console.log(`\n  ${G}✓${R} Merged into ${markdown.length.toLocaleString()} char document`);

  // Push to Linear
  if (!process.env.LINEAR_API_KEY) {
    console.log(`\n  ${Y}⚠${R} LINEAR_API_KEY not set — showing preview instead\n`);
    console.log(`${D}${"─".repeat(60)}${R}`);
    console.log(`${B}  Issue Title:${R} SYSTEM AUDIT: Ready for Launch`);
    console.log(`${B}  Priority:${R} ${Y}Urgent${R}`);
    console.log(`${B}  Label:${R} Audit-Complete`);
    console.log(`${B}  Body:${R} ${markdown.split("\n").length} lines of Markdown`);
    console.log(`${D}${"─".repeat(60)}${R}`);

    // Show TOC preview
    const tocLines = markdown.split("\n").slice(0, 20);
    for (const line of tocLines) {
      console.log(`  ${D}${line}${R}`);
    }
    console.log(`  ${D}...${R}\n`);

    console.log(`  ${G}✓${R} Audit report ready — set LINEAR_API_KEY to push to Linear`);
    console.log("");
    return;
  }

  console.log(`  ${C}[Linear]${R} Creating audit issue...`);
  const result = await createAuditIssue(markdown);
  console.log(`  ${G}✓${R} Issue created: ${B}${result.identifier}${R}`);
  console.log(`  ${D}${result.url}${R}\n`);
}

main().catch((err) => {
  console.error("Audit push failed:", err);
  process.exit(1);
});
