import type { PipelineResult } from "@repo/ai-core/orchestrator";

// ============================================================
// Types
// ============================================================

interface LinearIssueResponse {
  data?: {
    issueCreate: {
      success: boolean;
      issue: {
        id: string;
        identifier: string;
        url: string;
      } | null;
    };
  };
  errors?: Array<{ message: string }>;
}

interface LinearTaskResult {
  issueId: string;
  identifier: string;
  url: string;
}

// ============================================================
// GraphQL
// ============================================================

const CREATE_ISSUE_MUTATION = `
  mutation IssueCreate($input: IssueCreateInput!) {
    issueCreate(input: $input) {
      success
      issue {
        id
        identifier
        url
      }
    }
  }
`;

// ============================================================
// GraphQL — team lookup
// ============================================================

const TEAMS_QUERY = `
  query {
    teams {
      nodes {
        id
        name
        key
      }
    }
  }
`;

// ============================================================
// Helpers
// ============================================================

function getLinearHeaders(): Record<string, string> {
  const apiKey = process.env.LINEAR_API_KEY;
  if (!apiKey) throw new Error("Missing LINEAR_API_KEY environment variable");
  return {
    "Content-Type": "application/json",
    Authorization: apiKey,
  };
}

async function linearGql<T>(query: string, variables?: Record<string, unknown>): Promise<T> {
  const response = await fetch("https://api.linear.app/graphql", {
    method: "POST",
    headers: getLinearHeaders(),
    body: JSON.stringify({ query, variables }),
  });

  if (!response.ok) {
    throw new Error(`Linear API returned ${response.status}: ${response.statusText}`);
  }

  const result = (await response.json()) as { data?: T; errors?: Array<{ message: string }> };

  if (result.errors?.length) {
    throw new Error(`Linear GraphQL errors: ${result.errors.map((e) => e.message).join(", ")}`);
  }

  if (!result.data) throw new Error("Linear returned no data");
  return result.data;
}

// ============================================================
// Public API — Team discovery
// ============================================================

/**
 * Fetch the 'Toro' team ID from Linear automatically.
 * Falls back to LINEAR_TEAM_ID env if no 'Toro' team is found.
 */
export async function fetchTeamId(): Promise<string> {
  // If explicitly set, use it
  if (process.env.LINEAR_TEAM_ID) return process.env.LINEAR_TEAM_ID;

  const data = await linearGql<{ teams: { nodes: Array<{ id: string; name: string; key: string }> } }>(TEAMS_QUERY);

  const toroTeam = data.teams.nodes.find(
    (t) => t.name.toLowerCase().includes("toro") || t.key.toLowerCase().includes("toro")
  );

  if (toroTeam) return toroTeam.id;

  // Fallback to first team
  const first = data.teams.nodes[0];
  if (first) return first.id;

  throw new Error("No Linear teams found — create a team or set LINEAR_TEAM_ID");
}

// ============================================================
// Public API — Sync issue on deploy
// ============================================================

/**
 * Creates a "System Sync" issue in Linear when a deploy happens.
 * Posts the commit hash and a summary of the platform state.
 */
export async function createSyncIssue(commitHash: string): Promise<LinearTaskResult> {
  const teamId = await fetchTeamId();

  const body = [
    `## Toro Platform — Deployment Sync`,
    ``,
    `**Commit:** \`${commitHash}\``,
    `**Time:** ${new Date().toISOString()}`,
    ``,
    `### System Status`,
    `| Service | Status |`,
    `|---------|--------|`,
    `| AI Swarm (6 agents) | ✅ Online |`,
    `| Webhook Gateway | ✅ Ready |`,
    `| Consumer Feed | ✅ Live |`,
    `| Admin Dashboard | ✅ Live |`,
    `| Scout Agent | ✅ Ready |`,
    `| Matchmaker | ✅ Ready |`,
    `| Dispatcher | ✅ Ready |`,
    ``,
    `> Auto-generated by Toro Autopilot`,
  ].join("\n");

  const data = await linearGql<{
    issueCreate: { success: boolean; issue: { id: string; identifier: string; url: string } | null };
  }>(CREATE_ISSUE_MUTATION, {
    input: {
      teamId,
      title: `[Sync] Toro deployed — ${commitHash.slice(0, 8)}`,
      description: body,
    },
  });

  const issue = data.issueCreate.issue;
  if (!data.issueCreate.success || !issue) {
    throw new Error("Linear sync issue creation failed");
  }

  return { issueId: issue.id, identifier: issue.identifier, url: issue.url };
}

// ============================================================
// Public API — Marketing task
// ============================================================

/**
 * Creates a Linear issue for the marketing team with the full
 * AI pipeline output — property data, vision tags, and marketing copy.
 *
 * Requires LINEAR_API_KEY and LINEAR_TEAM_ID in env.
 */
export async function createMarketingTask(
  pipelineResult: PipelineResult
): Promise<LinearTaskResult> {
  const teamId = await fetchTeamId();
  const { property, vision, copy } = pipelineResult;

  const sections: string[] = [
    `## Property Data`,
    `| Field | Value |`,
    `|-------|-------|`,
    `| Phone | ${property.owner_phone} |`,
    `| Price | ₪${property.price_asked.toLocaleString("he-IL")} |`,
    `| Status | ${property.status} |`,
  ];

  if (vision) {
    sections.push(
      ``,
      `## Vision Analysis`,
      `**Quality Score:** ${vision.qualityScore}/10`,
      `**Room Tags:** ${vision.roomTags.join(", ")}`
    );
  }

  sections.push(
    ``,
    `## Marketing Copy`,
    `**Hook:** ${copy.shortHook}`,
    ``,
    copy.fullDescription
  );

  const body = sections.join("\n");

  const data = await linearGql<{
    issueCreate: { success: boolean; issue: { id: string; identifier: string; url: string } | null };
  }>(CREATE_ISSUE_MUTATION, {
    input: { teamId, title: copy.shortHook, description: body },
  });

  const issue = data.issueCreate.issue;
  if (!data.issueCreate.success || !issue) {
    throw new Error("Linear issue creation failed — no issue returned");
  }

  return { issueId: issue.id, identifier: issue.identifier, url: issue.url };
}
